### ISSUE TITLE
scriptexec always returns not found

### ISSUE THREAD

**Issue by awshidahak** [michael-lazar/pygopherd#1]
I have scriptexec enabled on my server. I have scripts that work using the python2 version of pygopherd, but no script seems to work on this python3 version. Whenever I call a script from either a web browser or gopher client, I get a not found output. On the web browser version, it renders an html error as text with http headers like so:

`HTTP/1.0 404 Not Found`
`Content-Type: text/html`

`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">`
`<HTML><HEAD><TITLE>Selector Not Found</TITLE>`
`        <H1>Selector Not Found</H1>`
`        <TT>No such file or directory</TT><HR>Pygopherd</BODY></HTML>`

I have pygopherd installed into the system as root, and running with the gopher user. Plain text documents serve just fine.

**Comment by michael-lazar** [comment]
It's tough to diagnose without seeing your filesystem and server configuration, but I've had this happen before too and it ended up being a file permission issue. The file does need to be globally executable (``S_IXOTH``) which is kind of a gotcha, but this was also the behavior in python2.

**Comment by awshidahak** [comment]
A file permission issue. Yes, the executable bit is set on the file. ls -l /var/gopher/qotwtxt will tell us this:

-rwxr-xr-x 1 gopher gopher 554 Sep 21 03:59 /var/gopher/qotwtxt

I can give you my full /etc/pygopherd/pygopherd.conf if that's what you mean by server configuration. 

[pygopherd.conf.txt](https://github.com/michael-lazar/pygopherd/files/7229133/pygopherd.conf.txt)

Renamed it to .txt for the upload. Is there anything else I can show you?

**Comment by awshidahak** [comment]
I fixed it by changing usechroot to no.
