### ISSUE TITLE
symlinks don't work

### ISSUE THREAD

**Issue by tomowad** [michael-lazar/pygopherd#3]
In an auto-generated directory listing, a symlink to a directory correctly displays the folder icon, but when I click it, I get the error:

```
Selector Not Found
'/path/to/symlink' does not exist (no handler found)
```

**Comment by michael-lazar** [comment]
Hi! There's not much I can do with this report unless you can give me instructions on how to reproduce your setup. If I had to take a stab in the dark, I would say check that the ``gopher`` user has permissions to access your symlinked file.

**Comment by tomowad** [comment]
The problem turned out to be that I had another broken symlink inside of that directory, and a broken symlink prevents pygopherd from loading the entire directory listing.
