### ISSUE TITLE
Error with HTTP side

### ISSUE THREAD

**Issue by ghost** [michael-lazar/pygopherd#6]
Gopher is working but if I use HTTP python display this error:
```
File "/usr/local/lib/python3.9/site-packages/pygopherd-3.0.0-py3.9.egg/pygopherd/handlers/base.py", line 35, in stat
ValueError: stat: embedded null character in path
```
My OS is FreeBSD 13.1 and I'm use python 3.9 with last PyGopherd from this repository

**Comment by michael-lazar** [comment]
Hi, that's a pretty interesting error!

Do you have a filename/directory with a null character in that path? What's your [file system](https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations)?

**Comment by ghost** [comment]
there doesn't seem to be any null characters. root directory gopher was /var/gopher
> What's your file system

Seems UFS (Standard in FreeBSD)

**Comment by michael-lazar** [comment]
I was able to repo by sending an encoded NUL character in the URL, e.g.

https://mozz.us:7070/%00

This is not really a valid link though, at least according to RFC 1436 gopher selectors can't contain null characters in them. Chrome won't even let me open that URL for security reasons, I had to use curl.

I would be curious if pygopgherd generated an invalid link for you (would be a pretty major bug), or if you got to it some other way. Or maybe someone is running a vulnerability scan against your server?

Either way, the best fix is probably for pygopherd to check for `\0` in the selector and throw a `GopherExceptions.FileNotFound` error. That's what most web servers do from a quick test, they return a generic 400 or a 404 error.

**Comment by ghost** [comment]
Vulnerability scanners seemed to touch only mine nginx(maybe delete it?), not 70 port. I'm wondering what to do in this case. Wait for a fix?

**Comment by michael-lazar** [comment]
> I'm wondering what to do in this case. Wait for a fix?

No this will not fix it, only make the error message a little better. In your case you have either:

- Something corrupt or weird inside your `/var/gopher/` directory
- Something corrupt or weird in your HTTP stack

One last shot in the dark, did you setup HTTP and HTTPS in your pygopherd configuration? If you haven't enabled the protocols it will fallback to gopher://. And if you are trying to send a TLS handshake over the gopher protocol it might explain this.

**Comment by ghost** [comment]
Maybe second. I'm try setting up http(s)

**Comment by ghost** [comment]
I'm found options for TLS and all working without error. Thx
